version: "3"

services:
  nginx:
    hostname: nginx
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ./server/static:/srv/www/src/static
      - ./server/media:/srv/www/src/media
      - ./server/logs:/srv/www/src/logs
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - client
      - server
  server:
    # hard start: docker-compose up --no-deps --force-recreate --build server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/srv/www/src
    expose:
      - 7000
    ports:
      - 7000:7000
    command: "python3 main.py"
  client:
    hostname: frontend
    build:
      context: .
      dockerfile: docker/elm/Dockerfile
    restart: always
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./client:/srv/www/src
      - /srv/www/src/node_modules
      - /srv/www/src/dist
    command: "npm run server"
  mongo:
    hostname: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/db
  mongo-express:
    hostname: mongo-express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - 8081:8081
