version: "3"

services:
  nginx:
    hostname: nginx
    # при падении будет стараться подняться
    restart: always
    # только свежий nginx
    image: nginx:latest
    # слушает порт 8080
    expose:
      - 8080
    # мапаем порт 80 на его 8080. Тогда сайт будет доступен по адресу localhost. Убедись, что порт у тебя не занят.
    ports:
      - "80:8080"
    # монтируем только те директории, в которых лежит статика, т.к. nginx с динамикой не будет работать. Также директорию с логами и файл настройки, который мы подготовили.
    volumes:
      - ./src/static:/srv/www/src/static
      - ./src/media:/srv/www/src/media
      - ./src/logs:/srv/www/src/logs
      - ./docker/nginx:/etc/nginx/conf.d
    # и nginx зависит от контейнера python. Т.е. python должен быть запущен первым
    depends_on:
      - client
      - server
  server:
    restart: always
    # указываем откуда собирать образ
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    # монтируем директорию проекта
    volumes:
      - .:/srv/www/src
    expose:
      - 7000
    ports:
      - 7000:7000
    command: "python3 /srv/www/src/main.py"
  client:
    hostname: frontend
    build:
      context: .
      dockerfile: docker/elm/Dockerfile
    restart: always
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./client:/srv/www/src
    command: "elm reactor --port 8000"
  mongo:
    hostname: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/db
  mongo-express:
    hostname: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
